# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# test
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      solr:
        image: solr:8
        ports:
        - "8983:8983"
        volumes:
          - data:/var/solr
        command:
          - solr-precreate
          - gettingstarted
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Create Solr container
      run: |
        docker run -d --name solr -p 8981:8983 solr:7 solr-precreate gettingstarted
    - run: |
        echo "Checking on the solr instance"
        curl http://localhost:8983/solr/admin/cores
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run compile --if-present
    - run: npm install -g istanbul
    - run: npm install --save-dev mocha chai
    - run: npm install -g coveralls
    - run: node_modules/.bin/istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --colors --reporter spec test/

